config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :new, :create] do
    member do
      patch :switch_role
    end
  end

  namespace :admin do
    resource :store, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :products, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    root 'stores#show'
  end

  resources :products, only: [:show, :index]

  root 'home#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
  has_many :products, dependent: :destroy

  # Add validations if necessary
  validates :name, presence: true
  validates :description, presence: true
  # validates :image_url, presence: true
end

app/controllers/admin/stores_controller.rb
module Admin
  class StoresController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_admin

    def show
      @store = current_user.store
    end

    def new
      @store = Store.new
    end

    def create
      @store = current_user.build_store(store_params)
      if @store.save
        redirect_to admin_store_path, notice: 'Store created successfully.'
      else
        render :new
      end
    end

    def edit
      @store = current_user.store
    end

    def update
      @store = current_user.store
      if @store.update(store_params)
        redirect_to admin_store_path, notice: 'Store updated successfully.'
      else
        render :edit
      end
    end

    def destroy
      @store = current_user.store
      @store.destroy
      redirect_to root_path, notice: 'Store deleted successfully.'
    end

    private

    def store_params
      params.require(:store).permit(:name, :description)
    end

    def authorize_admin
      redirect_to root_path, alert: 'You are not authorized to perform this action.' unless current_user.admin?
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def show
    # @store = Store.find(params[:id])
    @products = @store.products
  end

  def new
    @store = Store.new
  end

  def create
    @store = current_user.build_store(store_params)

    if @store.save
      current_user.update(role: :admin)
      redirect_to @store, notice: 'Store was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to @store, notice: 'Store was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
    redirect_to root_path, notice: 'Store was successfully deleted.'
  end


  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :description, :image_url)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Stores#create</h1>
  <p>Find me in app/views/stores/create.html.erb</p>
</div>

app/views/stores/new.html.erb
<%= form_with(model: @store, local: true) do |form| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>
      <ul>
        <% @store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit "Create Store" %>
  </div>
<% end %>

app/views/stores/show.html.erb
<!-- app/views/stores/show.html.erb -->
<h1><%= @store.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Image:</strong>
  <% if @store.image_url.present? %>
    <%= image_tag @store.image_url %>
  <% else %>
    <em>No image available</em>
  <% end %>
</p>

<h2>Products</h2>
<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %> - <%= number_to_currency(product.price) %>
        <p><%= product.description %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No products available for this store.</p>
<% end %>

<% if @store.user %>
  <p>Store Owner: <%= link_to @store.user.username, user_path(@store.user) %> </p>
<% end %>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Add Product', new_store_product_path(@store), class: 'btn btn-primary' %>
<% end %>