config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :new, :create] do
    member do
      patch :switch_role
    end
  end

  namespace :admin do
    resource :store, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :products, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    root 'stores#show'
  end

  resources :products, only: [:show, :index]

  root 'home#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { minimum: 6 }, if: :password_required?

  # Method to determine if password is required
  def password_required?
    new_record? || !password.nil?
  end
  
  enum role: { user: 0, admin: 1 }

  has_one :store, foreign_key: "user_id"
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :switch_role]
  before_action :authorize_admin, only: [:show]
  before_action :authorize_user_for_role_switch, only: [:switch_role]

  def index
    @users = User.all
  end

  def show
    if @user.nil?
      redirect_to users_path, alert: 'User not found'
    else
      @store = @user.store # Assuming a user has many stores
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "User created successfully!"
    else
      render :new
    end
  end

  def switch_role
    if @user.nil?
      redirect_to root_path, alert: 'User not found'
    else
      new_role = @user.role == 'admin' ? 'user' : 'admin'
      if @user.update(role: new_role)
        redirect_to root_path, notice: 'User role updated successfully.'
      else
        redirect_to root_path, alert: 'Failed to update user role.'
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def authorize_admin
    unless current_user.admin?
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end

  def authorize_user_for_role_switch
    unless current_user == @user
      redirect_to root_path, alert: 'You are not authorized to switch this user\'s role.'
    end
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Role</th>
      <th>Store</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user_path(user) %></td>
        <td><%= user.role %></td>
        <td>
          <% if user.stores.any? %>
            <%= link_to 'View Stores', user_path(user) %>
          <% else %>
            No Stores
          <% end %>
        </td>
        <td>
          <% if current_user.admin? && user != current_user %>
            <%= link_to 'Switch Role', switch_role_user_path(user), method: :patch, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to switch this user\'s role?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, url: users_path, method: :post do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>
  <br>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <br>

  <%= f.submit "Register", class: 'btn btn-primary' %>
<% end %>

<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<h2>Stores</h2>
<% if @stores.present? %>
  <ul>
    <% @stores.each do |store| %>
      <li>
        <%= link_to store.name, store_path(store) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No stores available</p>
<% end %>

<% if current_user.admin? && current_user != @user %>
  <%= link_to 'Switch Role', switch_role_user_path(@user), method: :patch, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to switch this user\'s role?' } %>
<% end %>