config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :new, :create] do
    member do
      patch :switch_role
    end
  end

  namespace :admin do
    resource :store, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :products, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    root 'stores#show'
  end

  resources :products, only: [:show, :index]

  root 'home#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
  has_many :products, dependent: :destroy

  # Add validations if necessary
  validates :name, presence: true
  validates :description, presence: true
  # validates :image_url, presence: true
end

app/controllers/admin/stores_controller.rb
module Admin
  class StoresController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_admin

    def show
      @store = current_user.store
    end

    def new
      @store = Store.new
    end

    def create
      @store = current_user.build_store(store_params)
      if @store.save
        redirect_to admin_store_path, notice: 'Store created successfully.'
      else
        render :new
      end
    end

    def edit
      @store = current_user.store
    end

    def update
      @store = current_user.store
      if @store.update(store_params)
        redirect_to admin_store_path, notice: 'Store updated successfully.'
      else
        render :edit
      end
    end

    def destroy
      @store = current_user.store
      @store.destroy
      redirect_to root_path, notice: 'Store deleted successfully.'
    end

    private

    def store_params
      params.require(:store).permit(:name, :description)
    end

    def authorize_admin
      redirect_to root_path, alert: 'You are not authorized to perform this action.' unless current_user.admin?
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def show
    # @store = Store.find(params[:id])
    @products = @store.products
  end

  def new
    @store = Store.new
  end

  def create
    @store = current_user.build_store(store_params)

    if @store.save
      current_user.update(role: :admin)
      redirect_to @store, notice: 'Store was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to @store, notice: 'Store was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
    redirect_to root_path, notice: 'Store was successfully deleted.'
  end


  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :description, :image_url)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/admin/stores/new.html.erb
<%= form_with(model: @store, url: admin_store_path, local: true) do |form| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>
      <ul>
        <% @store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit "Create Store" %>
  </div>
<% end %>

app/views/admin/stores/show.html.erb
<h1>Manage Store</h1>
<p>Name: <%= @store.name %></p>
<p>Description: <%= @store.description %></p>
<%= link_to 'Edit Store', edit_admin_store_path(@store), class: 'btn btn-secondary' %>
<%= link_to 'Delete Store', admin_store_path(@store), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to 'Add Product', new_admin_store_product_path(@store), class: 'btn btn-primary' %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to sign out?' } %>

<h2>Products</h2>
<% if @store.products.any? %>
  <ul>
    <% @store.products.each do |product| %>
      <li>
        <%= product.name %> - <%= link_to 'Edit', edit_admin_store_product_path(@store, product), class: 'btn btn-secondary' %> - <%= link_to 'Delete', admin_store_product_path(@store, product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No products available.</p>
<% end %>