config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :new, :create] do
    member do
      patch :switch_role
    end
  end

  namespace :admin do
    resource :store, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :products, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    root 'stores#show'
  end

  resources :products, only: [:show, :index]

  root 'home#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  # validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_admin
    before_action :set_store

    def index
      @products = @store.products
    end

    def new
      @product = @store.products.new
    end

    def create
      @product = @store.products.new(product_params)
      if @product.save
        redirect_to admin_store_products_path, notice: 'Product created successfully.'
      else
        render :new
      end
    end

    def edit
      @product = @store.products.find(params[:id])
    end

    def update
      @product = @store.products.find(params[:id])
      if @product.update(product_params)
        redirect_to admin_store_products_path, notice: 'Product updated successfully.'
      else
        render :edit
      end
    end

    def destroy
      @product = @store.products.find(params[:id])
      @product.destroy
      redirect_to admin_store_products_path, notice: 'Product deleted successfully.'
    end

    private

    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

    def authorize_admin
      redirect_to root_path, alert: 'You are not authorized to perform this action.' unless current_user.admin?
    end

    def set_store
      @store = current_user.store
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_store, only: [:new, :create]

  def new
    @product = @store.products.new
  end

  def create
    @product = @store.products.new(product_params)
    @product.user = current_user

    if @product.save
      redirect_to @store, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  private

  def set_store
    @store = Store.find(params[:store_id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :image_url)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, @store, @product], local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/new.html.erb
<!-- app/views/products/new.html.erb -->
<h1>New Product for <%= @store.name %></h1>

<%= form_with(model: [@store, @product], url: admin_store_products_path, local: true) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Store', admin_store_path(@store) %>